[phases.setup]
nixPkgs = ['...']

[phases.install]
cmds = ['composer install --no-interaction --optimize-autoloader']

[phases.build]
cmds = []

[env]
PHP_INI_POST_MAX_SIZE = "100M"
PHP_INI_UPLOAD_MAX_FILESIZE = "100M"

[start]
cmd = 'echo "Using railway.json startCommand"'
